import { Podcast } from './podcast';

export const PODCASTS: Podcast[] = [
 {id:1, name: 'The lottery of Life',background:"#5AB9C9", particpate: 'Dr Anat Chesner-Haviv', pic:'../assets/episode1.png', brief:'In the first episode, Dr. Anat Chesner will tell us about the lottery of life and the research that exists today that will keep you young for a longer period of time.', pro:'A Geneticist and a Nutritionist, working as Research Assistance at a Genetics laboratory in Bar ilan University.',pod:"https://www.podbean.com/media/player/hwk5i-b6a923?from=yiiadmin&download=1&version=1&skin=1&btn-skin=106&auto=1&download=1&pbad=1",credit:'', playButton:'#0A2B30'},
 {id:2,name:'Under Pressure',background:"#0A2B30",particpate: 'Dr Scott Sherr', pic:'../assets/brainEpisode.png',brief:"In the current episode Scott and I will talk about hyperbaric oxygen therapy and how it contributes to the fight against Alzheimer Parkinson's. Scott will explain his approach to preserving the body in a vital condition as we age. Studies show good results and risks are low, I came out highly optimistic about the future of hyperbaric oxygen therapy. Big credit to the guy's from under water adventures for allowing me to use their video from Their experience at Whipps cross Hospital in London.",pro:'Dr. Scott Sherr is a board-certified internal medicine physician with an additional certification in hyperbaric oxygen medicine',pod:"https://www.podbean.com/media/player/6du6d-b6c1d4?from=yiiadmin&download=1&version=1&skin=1&btn-skin=106&auto=1&download=1&pbad=1",credit:"../assets/scuba.jpg", playButton:'#ec2c22'},
 {id:3,name:'Mission Alpha',background:"#DACB0D",particpate: 'Mr. Sergey Young',pic:'../assets/alpha3.png', brief:'It is a great privilege for me to host Sergey Young. In the conversation, we brought his perspective and experience as an investor. In addition, we will discover an inspiring person who is willing to devote his time to pro bono work in order to create a world in which people are healthy and vital for many more years. We will talk about new innovations in the field and much more.',pro:'Sergey is a member in The Xprize Innovation Board and the co-founder of the Longevity vision fund, where he is devoting his time and money in order to achive a universal healthy long life',pod:'https://www.podbean.com/media/player/ekvu8-b76501?from=yiiadmin&download=1&version=1&skin=1&btn-skin=107&auto=1&download=1&pbad=1',credit:'',  playButton:''},
 {id:4,name:'Heaven on Earth',background:"#3C3F40",particpate: 'James Strole',pic:'../assets/jimi6.png', brief:"In today's episode  Heaven on Earth I host James Strole, James is actively from the 70s in the fight against death, his unique mindset allows him to live a powerfully life. We talked about RAADfest were you can find cutting edge innovation and leading entrepreneurs on the field of life extention. We covered more cool topics as agisem in work place, are infinty lives is Justified? Community and education for the era of longevity, an offer i can't refuse and much more",pro:"James is Co-founder and Co-director of People Unlimited, and the Director of the Coalition for Radical Life Extension, who are the producers of RAADfest.", pod:'https://www.podbean.com/media/player/86dtb-b76773?from=yiiadmin&download=1&version=1&skin=1&btn-skin=106&auto=1&download=1&pbad=1',credit:'', playButton:''},
 {id:5, name: 'Difficult but Solvable',background: '#5AB9C9', particpate: 'Mr. Nathan Rudnick', pic:'../assets/episode5.png', brief:"Nathan started his career in GMO in order to help feeding the world, but then slowly gut engage through his work with aging research. We are going to talk on what is the currect way to deal with Sarcopenia ? Are we going to grow meat flavored plants soon? Will we be able to plante pig organs in human ? crisper technologies and how is working it the Buck institute.", pro:'Nathan has a background in genetic engineering, As he worked at dupont for 9 years making GMO plants. Through his work he became interested in flavinoids and aging, ancestral genetic platforms that cause aging. Now he is working at the Buck institution currently developing 3D muscles for drug discovery and Sarcopenia interventions.',pod:"https://www.podbean.com/media/player/rxf4d-b768a9?from=yiiadmin&download=1&version=1&skin=1&btn-skin=106&auto=1&download=1&pbad=1",credit:'', playButton:'#0A2B30'},
 {id:6, name: 'Disruptive is Clarity',background: '#DACB0D', particpate: 'Liz Parrish', pic:'../assets/disClar1.png', brief:"In this episode, we have a unique chance to get a brief look at Bioviva's service and understand how their bioinformatics platform works. Liz explained what drove her to get into biotech and why she thinks the way drug development is done today, cost us in daily human life that could have been saved. Her main mission is to cure biological aging so she could then use the technology to find cures for children with diseases, and it starts with defining aging as a disease.", pro:'Liz is an advocate for creating stem cells and gene therapies, Shes the founder and CEO of Bioviva science, a disruptive bioinformatics company aiming to accelerate the development of gene therapies in order to save peoples lives. In 2015 she was the first to take 2 gene therapies to fight her own aging process.',pod: "https://www.podbean.com/media/player/b7fca-b811a9?from=yiiadmin&download=1&version=1&skin=1&btn-skin=107&auto=1&download=1&pbad=1" 
       ,credit:'', playButton:'#0A2B30'},
 {id:7, name: 'Movement to a future',background: '#3C3F40', particpate: 'Dr. Ilia Stambler', pic:'../assets/ep7.4.png', brief:"In this episode we discussed why longevity education is so important? Ilya's contribution and the seniority organization is an important example to the rest of the world because they began a discussion with the government about budgeting for old age research and preparing a national plan. What can be done in the short term? A lot !!!, even you can help.", pro:"Dr. Ilia Stambler sits in a unique position, he is Chief Science Officer of “Vetek” (Seniority) Association – The Senior Citizens Movement and the Director of research at Shmuel Harofe Geriatric Center.",pod: "https://www.podbean.com/media/player/pawxy-bb8c80?from=yiiadmin&download=1&version=1&skin=1&btn-skin=105&auto=1&share=1&fonts=Helvetica&download=1&rtl=0&pbad=1" ,credit:'', playButton:'#0A2B30'}
]
